# 정의 해야 할 것
# secrets:
#   APP_ID
#   BASE64_KEYSTORE
#   RELEASE_KEY_ALIAS
#   RELEASE_KEY_PASSWORD
#   RELEASE_STORE_PASSWORD
#   SLACK_CHANNEL_ID
#   SLACK_TOKEN
#   SLACK_WEBHOOK_URL
# vars:
#   APK_NAME

name: Build

on:
  push:
    branches:
      - main

env:
  JAVA_DISTRIBUTION: corretto
  JAVA_VERSION: 17
  COMPILE_SDK: 34
  MIN_SDK: 21
  TARGET_SDK: 34
  VERSION_CODE: ${{ github.run_number }}
  VERSION_NAME: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: "gradle"
      - uses: android-actions/setup-android@v2
      - run: |
          sudo chmod +x ./gradlew
        shell: bash
      - run: |
          echo ${{ secrets.BASE64_KEYSTORE }} | base64 -d > ./keystore
        shell: bash
      - name: Get MARVEL API Key
        run: |
          echo "publicKey=${{ secrets.MARVEL_PUBLIC_KEY }}" > local.properties
          echo "privateKey=${{ secrets.MARVEL_PRIVATE_KEY }}" >> local.properties
      - run: |
          echo "releaseKeyAlias=${{ secrets.RELEASE_KEY_ALIAS }}" > keystore.properties
          echo "releaseKeyPassword=${{ secrets.RELEASE_KEY_PASSWORD }}" >> keystore.properties
          echo "releaseKeyStore=keystore" >> keystore.properties
          echo "releaseStorePassword=${{ secrets.RELEASE_STORE_PASSWORD }}" >> keystore.properties
        shell: bash
      - run: ./gradlew androidDependencies
        shell: bash
      - run: ./gradlew dependencyUpdates -Drevision=release -DoutputFormatter=plain
        shell: bash
      - run: |
          echo applicationId=${{ secrets.APP_ID }} > build.properties
          echo compileSdk=${{ env.COMPILE_SDK }} >> build.properties
          echo minSdk=${{ env.MIN_SDK }} >> build.properties
          echo targetSdk=${{ env.TARGET_SDK }} >> build.properties
          echo versionCode=${{ env.VERSION_CODE }} >> build.properties
          echo versionName=${{ env.VERSION_NAME }} >> build.properties
        shell: bash
      - run: ./gradlew assembleRelease bundleRelease
        shell: bash
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,ref # repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
      - name: Change File Name
        run: |
          mkdir artifacts
          mv app/build/outputs/apk/release/app-release.apk artifacts/${{ vars.APK_NAME }}-${{ env.VERSION_CODE }}.apk
          mv app/build/outputs/bundle/release/app-release.aab artifacts/${{ vars.APK_NAME }}-${{ env.VERSION_CODE }}.aab
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ vars.APK_NAME }}-${{ env.VERSION_CODE }}
          path: artifacts/*.*
      - name: Slack Upload Artifacts
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: 'artifacts/*.*'